### PR TITLE
Added InputPhone.

### PR DESCRIPTION
**Pull request by jepsar**

### CODE REVIEW

**Comment by jepsar** [comment]
The only thing I could not get to work was the "new" indicator.

**Comment by jepsar** [comment]
Oh.. and contentTab2 doesn't show up! I don't see any typos in the file path, don't know what's going on there.

**Comment by melloware** [comment]
I will fix everything as I test it.

**Comment by melloware** [comment]
Please review this showcase commit: https://github.com/primefaces-extensions/showcase/commit/f7b4511a84eca7e375014d72f88410ca5a615b71

Everything is working for me including the two tab decorator and the "New" logo next to inputphone.

**Comment by jepsar** [comment]
The only issue I found is https://github.com/primefaces-extensions/showcase/commit/f7b4511a84eca7e375014d72f88410ca5a615b71#r32495417

**Pull request merged**
